config/routes.rb
Rails.application.routes.draw do
  get 'session/sign_in'

  resources :patients
  resources :contact_messages
  resources :dentists
  resources :users

end

app/models/contact_message.rb
class ContactMessage < ActiveRecord::Base
end

app/controllers/contact_messages_controller.rb
class ContactMessagesController < ApplicationController
  before_action :set_contact_message, only: [:show, :edit, :update, :destroy]

  layout "manager"
  # GET /contact_messages
  # GET /contact_messages.json
  def index
    @contact_messages = ContactMessage.all
  end

  # GET /contact_messages/1
  # GET /contact_messages/1.json
  def show
  end

  # GET /contact_messages/new
  def new
    @contact_message = ContactMessage.new
  end

  # GET /contact_messages/1/edit
  def edit
  end

  # POST /contact_messages
  # POST /contact_messages.json
  def create
    @contact_message = ContactMessage.new(contact_message_params)

    respond_to do |format|
      if @contact_message.save
        format.html { redirect_to @contact_message, notice: 'Contact message was successfully created.' }
        format.json { render :show, status: :created, location: @contact_message }
      else
        format.html { render :new }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_messages/1
  # PATCH/PUT /contact_messages/1.json
  def update
    respond_to do |format|
      if @contact_message.update(contact_message_params)
        format.html { redirect_to @contact_message, notice: 'Contact message was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_message }
      else
        format.html { render :edit }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_messages/1
  # DELETE /contact_messages/1.json
  def destroy
    @contact_message.destroy
    respond_to do |format|
      format.html { redirect_to contact_messages_url, notice: 'Contact message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_message
      @contact_message = ContactMessage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_message_params
      params.require(:contact_message).permit(:name, :phone_no, :email, :message)
    end
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/views/contact_messages/_form.html.erb
<section class="panel">
    <header class="panel-heading">
      Add New Lecturer
    </header>
      
    <div class="panel-body table-responsive">



      <%= form_for(@contact_message) do |f| %>
        <% if @contact_message.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@contact_message.errors.count, "error") %> prohibited this contact_message from being saved:</h2>

            <ul>
            <% @contact_message.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone_no %><br>
          <%= f.text_field :phone_no, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :message %><br>
          <%= f.text_field :message, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>

    </div>
</section>      

app/views/contact_messages/edit.html.erb
<h1>Editing Contact Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_message %> |
<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/index.html.erb
<section class="panel">
    <header class="panel-heading">
            My Sections
    </header>
    <div class="panel-body table-responsive">


<p id="notice"><%= notice %></p>

<h1>Listing Contact Messages</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone no</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_messages.each do |contact_message| %>
      <tr>
        <td><%= contact_message.name %></td>
        <td><%= contact_message.phone_no %></td>
        <td><%= contact_message.email %></td>
        <td><%= contact_message.message %></td>
        <td><%= link_to 'Show', contact_message %></td>
        <td><%= link_to 'Edit', edit_contact_message_path(contact_message) %></td>
        <td><%= link_to 'Destroy', contact_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
</section>

<%= link_to 'New Contact message', new_contact_message_path %>

app/views/contact_messages/new.html.erb
<h1>New Contact Message</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_messages_path %>

app/views/contact_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact_message.name %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @contact_message.phone_no %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact_message.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact_message.message %>
</p>

<%= link_to 'Edit', edit_contact_message_path(@contact_message) %> |
<%= link_to 'Back', contact_messages_path %>