config/routes.rb
Rails.application.routes.draw do
  get 'session/sign_in'

  resources :patients
  resources :contact_messages
  resources :dentists
  resources :users

end

app/models/dentist.rb
class Dentist < ActiveRecord::Base
end

app/controllers/dentists_controller.rb
class DentistsController < ApplicationController
  before_action :set_dentist, only: [:show, :edit, :update, :destroy]

  layout "manager"
  # GET /dentists
  # GET /dentists.json
  def index
    @dentists = Dentist.all
  end

  # GET /dentists/1
  # GET /dentists/1.json
  def show
  end

  # GET /dentists/new
  def new
    @dentist = Dentist.new
  end

  # GET /dentists/1/edit
  def edit
  end

  # POST /dentists
  # POST /dentists.json
  def create
    @dentist = Dentist.new(dentist_params)

    respond_to do |format|
      if @dentist.save
        format.html { redirect_to @dentist, notice: 'Dentist was successfully created.' }
        format.json { render :show, status: :created, location: @dentist }
      else
        format.html { render :new }
        format.json { render json: @dentist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dentists/1
  # PATCH/PUT /dentists/1.json
  def update
    respond_to do |format|
      if @dentist.update(dentist_params)
        format.html { redirect_to @dentist, notice: 'Dentist was successfully updated.' }
        format.json { render :show, status: :ok, location: @dentist }
      else
        format.html { render :edit }
        format.json { render json: @dentist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dentists/1
  # DELETE /dentists/1.json
  def destroy
    @dentist.destroy
    respond_to do |format|
      format.html { redirect_to dentists_url, notice: 'Dentist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dentist
      @dentist = Dentist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dentist_params
      params.require(:dentist).permit(:name, :email, :phone_no, :registered_dental_no, :isActive)
    end
end

app/helpers/dentists_helper.rb
module DentistsHelper
end

app/views/dentists/_form.html.erb
<section class="panel">
    <header class="panel-heading">
      Add New Lecturer
    </header>
      
    <div class="panel-body table-responsive">




      <%= form_for(@dentist) do |f| %>
        <% if @dentist.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@dentist.errors.count, "error") %> prohibited this dentist from being saved:</h2>

            <ul>
            <% @dentist.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email %><br>
          <%= f.text_field :email, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone_no %><br>
          <%= f.text_field :phone_no, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :registered_dental_no %><br>
          <%= f.text_field :registered_dental_no, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :isActive %><br>
          <%= f.check_box :isActive, class: 'form-control' %>
        </div>
        <div class="actions">
          <%= f.submit %>
        </div>
      <% end %>

</div>
</section>

app/views/dentists/edit.html.erb
<h1>Editing Dentist</h1>

<%= render 'form' %>

<%= link_to 'Show', @dentist %> |
<%= link_to 'Back', dentists_path %>

app/views/dentists/index.html.erb
<section class="panel">
    <header class="panel-heading">
            My Sections
    </header>
    <div class="panel-body table-responsive">

      <p id="notice"><%= notice %></p>


<h1>Listing Dentists</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone no</th>
      <th>Registered dental no</th>
      <th>Isactive</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dentists.each do |dentist| %>
      <tr>
        <td><%= dentist.name %></td>
        <td><%= dentist.email %></td>
        <td><%= dentist.phone_no %></td>
        <td><%= dentist.registered_dental_no %></td>
        <td><%= dentist.isActive %></td>
        <td><%= link_to 'Show', dentist %></td>
        <td><%= link_to 'Edit', edit_dentist_path(dentist) %></td>
        <td><%= link_to 'Destroy', dentist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
</section>
<%= link_to 'New Dentist', new_dentist_path %>

app/views/dentists/new.html.erb
<h1>New Dentist</h1>

<%= render 'form' %>

<%= link_to 'Back', dentists_path %>

app/views/dentists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dentist.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @dentist.email %>
</p>

<p>
  <strong>Phone no:</strong>
  <%= @dentist.phone_no %>
</p>

<p>
  <strong>Registered dental no:</strong>
  <%= @dentist.registered_dental_no %>
</p>

<p>
  <strong>Isactive:</strong>
  <%= @dentist.isActive %>
</p>

<%= link_to 'Edit', edit_dentist_path(@dentist) %> |
<%= link_to 'Back', dentists_path %>